# Generated by Django 4.1.1 on 2022-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='(83)99999-9999', max_length=21, null=True, verbose_name='telefone'),
        ),
    ]
