# Generated by Django 4.1.1 on 2022-10-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_remove_usuario_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default='', max_length=150, verbose_name='Nome'),
        ),
    ]
